CREATE USER daily WITH
    LOGIN
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOINHERIT
    NOREPLICATION
    PASSWORD 'daily';

GRANT CONNECT ON DATABASE daily TO daily;
--GRANT CONNECT ON DATABASE daily_96rj TO daily;

GRANT daily TO admin;

CREATE SCHEMA IF NOT EXISTS flyway
    AUTHORIZATION daily;

CREATE SCHEMA IF NOT EXISTS "user"
    AUTHORIZATION daily;

GRANT USAGE ON SCHEMA "user" TO daily;

CREATE SCHEMA IF NOT EXISTS daily
    AUTHORIZATION daily;

GRANT USAGE ON SCHEMA daily TO daily;
