CREATE SCHEMA IF NOT EXISTS flyway AUTHORIZATION daily;
CREATE SCHEMA IF NOT EXISTS "user" AUTHORIZATION daily;
GRANT USAGE ON SCHEMA "user" TO daily;

CREATE SCHEMA IF NOT EXISTS daily AUTHORIZATION daily;
GRANT USAGE ON SCHEMA daily TO daily;
